# keywords for mavlink messages
GIMBAL_DEVICE_ATTITUDE_STATUS_KEYWORD = "GIMBAL_DEVICE_ATTITUDE_STATUS"
MOUNT_ORIENTATION_KEYWORD             = "MOUNT_ORIENTATION"
RAW_IMU_KEYWORD                       = "RAW_IMU"
MOUNT_STATUS_KEYWORD                  = "MOUNT_STATUS"
SYS_STATUS_KEYWORD                    = "SYS_STATUS"
COMMAND_ACK_KEYWORD                   = "COMMAND_ACK"
HEARTBEAT_KEYWORD                     = "HEARTBEAT"
PARAM_VALUE_KEYWORD                   = "PARAM_VALUE"

# MAVLink parameter IDs
PARAM_STIFF_TILT       = "STIFF_TILT"       # pitch stiffness     [0-100]
PARAM_STIFF_ROLL       = "STIFF_ROLL"       # roll stiffness      [0-100]
PARAM_STIFF_PAN        = "STIFF_PAN"        # yaw stiffness       [0-100]
PARAM_PWR_TILT         = "PWR_TILT"         # pitch hold strength [0-100]
PARAM_PWR_ROLL         = "PWR_ROLL"         # roll hold strength  [0-100]
PARAM_PWR_PAN          = "PWR_PAN"          # yaw hold strength   [0-100]
PARAM_FILTER_OUT       = "FILTER_OUT"       # output filter       [0-100]
PARAM_GYRO_LPF         = "GYRO_LPF"         # gyro LPF filter     [0-100]
PARAM_FLW_SP_TILT      = "FLW_SP_TILT"      # follow speed  - pitch [deg/s]
PARAM_FLW_SP_PAN       = "FLW_SP_PAN"       # follow speed  - yaw   [deg/s]
PARAM_FLW_LPF_TILT     = "FLW_LPF_TILT"     # follow smooth - pitch [0-100]
PARAM_FLW_LPF_PAN      = "FLW_LPF_PAN"      # follow smooth - yaw   [0-100]
PARAM_FLW_WD_TILT      = "FLW_WD_TILT"      # follow window - pitch [degrees]
PARAM_FLW_WD_PAN       = "FLW_WD_PAN"       # follow window - yaw   [degrees]
PARAM_RC_LPF_TILT      = "RC_LPF_TILT"      # command smooth - pitch [0-100]
PARAM_RC_LPF_ROLL      = "RC_LPF_ROLL"      # command smooth - roll  [0-100]
PARAM_RC_LPF_PAN       = "RC_LPF_PAN"       # command smooth - yaw   [0-100]
PARAM_RC_SPD_TILT      = "RC_SPD_TILT"      # command speed - pitch [deg/s]
PARAM_RC_SPD_ROLL      = "RC_SPD_ROLL"      # command speed - roll  [deg/s]
PARAM_RC_SPD_PAN       = "RC_SPD_PAN"       # command speed - yaw   [deg/s] 
PARAM_RC_LIM_MIN_TILT  = "RC_LIM_MIN_TILT"  # pitch min limit [degrees]
PARAM_RC_LIM_MAX_TILT  = "RC_LIM_MAX_TILT"  # pitch max limit [degrees]
PARAM_RC_LIM_MIN_ROLL  = "RC_LIM_MIN_ROLL"  # roll  min limit [degrees]
PARAM_RC_LIM_MAX_ROLL  = "RC_LIM_MAX_ROLL"  # roll  max limit [degrees]
PARAM_RC_LIM_MIN_PAN   = "RC_LIM_MIN_PAN"   # yaw   min limit [degrees]
PARAM_RC_LIM_MAX_PAN   = "RC_LIM_MAX_PAN"   # yaw   max limit [degrees]
PARAM_TILT_DAMPING     = "TILT_DAMPING"     # pitch damping [0-100]
PARAM_ROLL_DAMPING     = "ROLL_DAMPING"     # roll  damping [0-100]
PARAM_PAN_DAMPING      = "PAN_DAMPING"      # yaw   damping [0-100]
PARAM_VERSION_X        = "VERSION_X"        # firmware version major
PARAM_VERSION_Y        = "VERSION_Y"        # firmware version minor
PARAM_VERSION_Z        = "VERSION_Z"        # firmware version patch
PARAM_SRL_NUMBER       = "SRL_NUMBER"       # serial number
PARAM_GMB_HOME_PAN     = "GMB_HOME_PAN"     # home pan angle           [degrees]
PARAM_MAPPING_ANGLE    = "MAPPING_ANGLE"    # mapping mode tilt angle  [degrees]
PARAM_GYRO_TRUST       = "GYRO_TRUST"       # gyro sensor trust        [0-255]
PARAM_RC_DZONE_TILT    = "RC_DZONE_TILT"    # RC dead-zone - pitch [0-100]
PARAM_RC_DZONE_ROLL    = "RC_DZONE_ROLL"    # RC dead-zone - roll  [0-100]
PARAM_RC_DZONE_PAN     = "RC_DZONE_PAN"     # RC dead-zone - yaw   [0-100]
PARAM_RC_MODE_TILT     = "RC_MODE_TILT"     # RC mode - pitch [0/1]
PARAM_RC_MODE_ROLL     = "RC_MODE_ROLL"     # RC mode - roll  [0/1]
PARAM_RC_MODE_PAN      = "RC_MODE_PAN"      # RC mode - yaw   [0/1]
PARAM_RC_CHAN_STILT    = "RC_CHAN_STILT"    # RC channel - stilt/tilt speed
PARAM_RC_CHAN_SPAN     = "RC_CHAN_SPAN"     # RC channel - span/pan speed
PARAM_RC_CHAN_TILT     = "RC_CHAN_TILT"     # RC channel - tilt angle
PARAM_RC_CHAN_ROLL     = "RC_CHAN_ROLL"     # RC channel - roll angle
PARAM_RC_CHAN_PAN      = "RC_CHAN_PAN"      # RC channel - pan angle
PARAM_RC_CHAN_MODE     = "RC_CHAN_MODE"     # RC channel - mode switch
PARAM_RC_TRIM_TILT     = "RC_TRIM_TILT"     # RC trim - pitch [degrees]
PARAM_RC_TRIM_ROLL     = "RC_TRIM_ROLL"     # RC trim - roll  [degrees]
PARAM_RC_TYPE          = "RC_TYPE"          # RC input type
PARAM_RC_REVERSE_AXIS  = "RC_REVERSE_AXIS"  # RC axis reversal bitmask
PARAM_MAV_EMIT_HB      = "MAV_EMIT_HB"      # emit heartbeat              [0/1]
PARAM_MAV_TS_ENCNT     = "MAV_TS_ENCNT"     # encoder count timestamp     [0/1]
PARAM_MAV_RATE_ST      = "MAV_RATE_ST"      # SYS_STATUS rate             [Hz]
PARAM_MAV_RATE_ENCCNT  = "MAV_RATE_ENCCNT"  # MOUNT_STATUS rate           [Hz]
PARAM_MAV_RATE_ORIEN   = "MAV_RATE_ORIEN"   # MOUNT_ORIENTATION rate      [Hz]
PARAM_MAV_RATE_IMU     = "MAV_RATE_IMU"     # RAW_IMU rate                [Hz]
PARAM_BAUDRATE_COM2    = "BAUDRATE_COM2"    # baud rate COM2 (×100, e.g. 1152 = 115200)
PARAM_BAUDRATE_COM4    = "BAUDRATE_COM4"    # baud rate COM4 (×100)
PARAM_GIMBAL_COMPID    = "GIMBAL_COMPID"    # gimbal MAVLink component ID